# Generated by Django 3.0.6 on 2020-05-11 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manufacturer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Console',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=2999)),
                ('price', models.FloatField()),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturer.Manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ConsoleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(max_length=999)),
                ('console', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.Console')),
            ],
        ),
        migrations.AddField(
            model_name='console',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='console.ConsoleType'),
        ),
    ]
