# Generated by Django 3.0.6 on 2020-05-15 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0002_auto_20200515_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='console',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
